DEV-1756 Modify/clean up toggle card
OffTheRecordApp/otr_ui_shared_components pull request #17
Opened 2023-01-05 01:06 UTC by SKona306

This PR will:

- Add binding to allow user to control whether icon is visible on toggle card
- Modify loading spinner to replace toggle while loading

### Wait to merge until:

- Design review with Alex
- Other PR in UI-shared-components is merged
- version is updated

2023-01-05 16:53 UTC, Morkos requested changes
Few comments below

2023-01-05 16:53 UTC, Morkos commented on app/components/app-toggle-card.component.scss
> +    border-left-color: green !important;
where is the conflict that makes have to put !important?

2023-01-05 16:53 UTC, Morkos commented on app/components/toggle-card/app-toggle-card.component.html
> +            <div ng-if="vm.isIconShowing">
isIconVisible

2023-01-05 16:53 UTC, Morkos commented on app/components/toggle-card/app-toggle-card.component.ts
> +    isIconShowing: boolean;
isIconVisible

2023-01-05 19:57 UTC, SKona306 commented on app/components/app-toggle-card.component.scss
> +    border-left-color: green !important;
removed. not needed after pulling changes from main branch

2023-01-06 00:12 UTC, JStein92 approved these changes
Nice work!

2023-01-06 17:36 UTC, merged