DEV-1026 Stat/Toggle cards V2 add dynamic height/width
OffTheRecordApp/otr_ui_shared_components pull request #6
Opened 2022-06-02 17:18 UTC by SKona306

This PR should enable the ability to control the stat cards and toggle cards height and width dynamically by controlling the parent containers height and width. One note is that it seems you can't just use min-height property without also specifying a static height property; Let me know if you think this will be an issue.

2022-06-02 18:41 UTC, Morkos requested changes
Lookin' good! Two comments below

2022-06-02 18:41 UTC, Morkos commented on app/components/app-toggle-card.component.scss
>  .toggle-card {
good addition here to prevent CSS conflicts. You can remove the nested .toggle-card then since it's redundant

2022-06-02 18:41 UTC, Morkos commented on index-test.html
> +          update-toggle="updateVacationMode()"
change the bindings to

is-enabled
on-switch-click

2022-06-02 18:57 UTC, JStein92 reviewed
This is cool! Very flexible component. Approved once Mark's comments are addressed.

2022-06-02 19:11 UTC, SKona306 commented
I ended up removing the app-toggle-card styling as it is not necessary. let me know if you would still like me to switch up the naming schemes for the css on toggle cards.

2022-06-02 19:35 UTC, Morkos reviewed
Looking good! Two comments to rename the top-level CSS class for stat card and toggle card

2022-06-02 19:35 UTC, Morkos commented on app/components/app-stat-card.component.scss
>  .stat-card {
rename to app-stat-card

2022-06-02 19:35 UTC, Morkos commented on app/components/app-toggle-card.component.scss
rename .toggle-card to .app-toggle-card

2022-06-06 23:58 UTC, Morkos approved these changes
LGTM!

2022-06-06 23:58 UTC, merged